# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

test:
  script:
      - npm install
      - npm run test

build:
    script:
        - npm run build
