cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

stages:
  - install_dependencies
  - test
  - build

install_dependencies:
  stage: install_dependencies
  script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules/

lint:
  stage: test
  needs: ["install_dependencies"]
  script:
    - npm run lint

unit_test:
  stage: test
  needs: ["install_dependencies"]
  script:
    - npm run test
  coverage: /All files\s*\|\s*([\d\.]+)/

build_app:
  stage: build
  needs: ["lint", "unit_test"]
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main"'
